### ISSUE TITLE
[question] Why not check that arguments are used?

### ISSUE THREAD

**Issue by uiureo** [feross/eslint-config-standard#19]
I expected `"bar" is defined but never used` in this code, but got nothing. 

```js
function foo (bar) { 
  return true
}
foo()
```

I've found it's because of this setting. But I couldn't find the reason.

```
"no-unused-vars": [2, { "vars": "all", "args": "none" }],
```
https://github.com/feross/eslint-config-standard/blob/master/eslintrc.json#L104
http://eslint.org/docs/rules/no-unused-vars.html#args

I think it should be `{ "args": "all" }` or `{ "args": "after-used" }`.

It seems this change was made in this commit.
https://github.com/feross/standard/commit/72765c25507bb1b459dddaa6a8f57f28b180e5a9#diff-da50a6bc6687fde49b3a83e1f9ad2c4fR97

Is there still any reason that it doesn't check arguments?

**Comment by feross** [comment]
The reason was, for me at least, that express (the web framework) requires a certain number of arguments to a middleware for it to be considered an error handling middleware:

```js
app.use(function(err, req, res, next) {
  // logic
})
```

In principle this rule is decent, and could help catch errors. But it might be too late to stick this in there, unless we add 

Here's a test run on the top ~400 packages that use `standard` based on npm dependency count:

```
# tests 427
# pass  301
# fail  126
```

with this setting:

```
    "no-unused-vars": [2, { "vars": "all", "args": "after-used" }]
```

So, maybe this will have to wait until there's a [standard-strict](https://github.com/feross/standard/issues/382) or a future major version.

**Comment by uiureo** [comment]
Makes sense. Thanks for response!
