### ISSUE TITLE
Lint Fenced Code in Markdown File

### ISSUE THREAD

**Issue by kemitchell** [feross/eslint-config-standard#43]
Would you be open to a PR adding an [ESLint Markdown Plugin](https://github.com/eslint/eslint-plugin-markdown) to apply Standard rules to fenced code in Markdown files?

**Comment by feross** [comment]
My first reaction is this it feels like feature creep to include this in `standard`...

There would be a lot of false positives on rules like `no-undef` and `no-unused-vars` because code snippets are not complete files.

However, there's already a project for linting your markdown files, and it even takes into account which rules make sense to ignore inside of markdown snippets. See: https://github.com/zeke/standard-markdown

**Comment by kemitchell** [comment]
Geez. Sought, but did not find. And it's Zeke, of all people...

**Comment by feross** [comment]
👍 @zeke
