### ISSUE TITLE
why set 'sourceType' to `module`?

### ISSUE THREAD

**Issue by flowmemo** [feross/eslint-config-standard#66]
'standard' style is my favorite coding style. Now I want to add the rule 'strict'(http://eslint.org/docs/rules/strict) for my project, but I find this rule doesn't work when `sourceType` is `module`(http://eslint.org/docs/rules/strict#rule-details). Finally, I can solve this problem by set the `parserOptions` manually in the config file.

Out of curiosity, why set 'sourceType' to `module`?

I try to remove this option. It can pass tests of `eslint-config-standard` and `standard`(see https://travis-ci.org/flowmemo/standard/jobs/192968809, I remove the option from  node_modules/eslint-config-standard/eslintrc.json).

Thanks.

**Comment by feross** [comment]
We set the sourceType to 'module' so the parser can parse JS files that are modules. Fortunately, with this option set parsing normal files works just fine. Feel free to override for your own use case.

**Comment by Raynos** [comment]
This settings breaks the use strict rule :(

My commonJS file is not a module, it's a script. Standardx does not overwrite it either -.-

**Comment by mightyiam** [comment]
@Raynos could you provide an example, please?

**Comment by Raynos** [comment]
Never mind, i figured out a typo in my package.json -.-

You can use `standardx` to overwrite the `moduleType: "script"` 

So it can be worked around.

However https://eslint.org/docs/rules/strict says that a "ES module using import/export" must not have `'use strict';` and a commonJS module must have `'use strict'`

Because `standard` globally opts into `moduleType: "module"` for code that is not an ES module using import/export but is actually a commonJS file the `strict` rule does not behave as you would expect.

**Comment by Raynos** [comment]
I don't think there's a good fix other then for something like `.mjs` / `.cjs` / read package.json module type with node ESM.

For babel faux modules code its just :disappointed:

**Comment by N0wan** [comment]
Actually, the strict mode is automatically enabled in module files.
That's why the "use strict" line is too much.
